- name: Create isucari directory
  become: yes
  become_user: isucon
  file:
    path=/home/isucon/isucari
    state=directory

- name: Deploy isucari
  become: yes
  synchronize:
    src: ../../../../
    dest: /home/isucon/isucari
    delete: no
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.gitignore"
      - "--exclude=provisioning"
      - "--exclude=webapp/public/upload"
      - "--exclude=initial-data/images"

- name: Chown isucon
  become: yes
  file:
    dest: /home/isucon/isucari
    owner: isucon
    group: isucon
    mode: 0755
    recurse: yes
